const express = require("express");
const multer = require("multer");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const { requireAdminAuth } = require("./admin");

const router = express.Router();

const projectsDirectory = path.join(__dirname, "projects");
const mediaConfigPath = path.join(__dirname, "..", "media.json");

if (!fs.existsSync(projectsDirectory)) {
  fs.mkdirSync(projectsDirectory, { recursive: true });
}

const DEFAULT_MEDIA_CONFIG = {
  homepage: {
    banner: null,
    introduction: null,
    finale: null,
    gallery: { facades: [] },
  },
};

const HOMEPAGE_SLOTS = ["banner", "introduction", "finale"];

function createMediaUrl(filename) {
  return `/api/media/file/${encodeURIComponent(filename)}`;
}

function checkFileExists(filename) {
  if (!filename) return false;

  try {
    const cleanName = path.basename(filename);
    const filePath = path.join(projectsDirectory, cleanName);

    return fs.existsSync(filePath);
  } catch {
    return false;
  }
}

function readMediaConfig() {
  try {
    if (!fs.existsSync(mediaConfigPath)) {
      fs.writeFileSync(
        mediaConfigPath,
        JSON.stringify(DEFAULT_MEDIA_CONFIG, null, 2),
        "utf8"
      );

      return DEFAULT_MEDIA_CONFIG;
    }

    const raw = fs.readFileSync(mediaConfigPath, "utf8");

    if (!raw.trim()) {
      return DEFAULT_MEDIA_CONFIG;
    }

    const parsed = JSON.parse(raw);

    const facades =
      parsed.homepage?.gallery?.facades ||
      parsed.homepage?.gallery?.facade ||
      [];

    return {
      homepage: {
        banner: parsed.homepage?.banner ?? null,
        introduction: parsed.homepage?.introduction ?? null,
        finale: parsed.homepage?.finale ?? null,
        gallery: {
          facades: Array.isArray(facades) ? facades : [facades],
        },
      },
    };
  } catch (err) {
    console.error("❌ Erreur lecture media.json:", err.message);

    return DEFAULT_MEDIA_CONFIG;
  }
}

function writeMediaConfig(config) {
  try {
    fs.writeFileSync(
      mediaConfigPath,
      JSON.stringify(config, null, 2),
      "utf8"
    );

    return true;
  } catch (err) {
    console.error("❌ Erreur écriture media.json:", err.message);

    return false;
  }
}

/*
|--------------------------------------------------------------------------
| GET ALL MEDIA (PUBLIC)
|--------------------------------------------------------------------------
|
| IMPORTANT:
| Files uploaded by this server are named:
|
|     Date.now()-randomhex.ext
|
| Therefore the Date.now() prefix is the most reliable upload ordering
| mechanism.
|
| Newest media is ALWAYS returned first.
|
*/
router.get("/", (req, res) => {
  try {
    if (!fs.existsSync(projectsDirectory)) {
      return res.status(200).json({
        success: true,
        media: [],
      });
    }

    const files = fs.readdirSync(projectsDirectory, {
      withFileTypes: true,
    });

    const media = files
      .filter((entry) => entry.isFile())
      .map((entry) => {
        const fullPath = path.join(projectsDirectory, entry.name);

        let timestamp = 0;

        /*
         * PRIMARY ORDERING METHOD
         *
         * Uploaded files generated by multer have:
         *
         *     1756638123456-a8f92c....jpg
         *
         * The first number is Date.now().
         */
        const match = entry.name.match(/^(\d{13})[-_]/);

        if (match) {
          const parsedTimestamp = Number(match[1]);

          if (
            Number.isFinite(parsedTimestamp) &&
            parsedTimestamp > 0
          ) {
            timestamp = parsedTimestamp;
          }
        }

        /*
         * FALLBACK
         *
         * For older files that don't have the Date.now() prefix,
         * use the filesystem timestamps.
         */
        if (timestamp === 0) {
          try {
            const stats = fs.statSync(fullPath);

            timestamp = Math.max(
              Number(stats.birthtimeMs) || 0,
              Number(stats.mtimeMs) || 0,
              Number(stats.ctimeMs) || 0
            );
          } catch {
            timestamp = 0;
          }
        }

        return {
          id: entry.name,
          name: entry.name,
          url: createMediaUrl(entry.name),
          timestamp,
        };
      })
      /*
       * NEWEST FIRST
       *
       * Larger timestamp = newer file.
       */
      .sort((a, b) => {
        if (b.timestamp !== a.timestamp) {
          return b.timestamp - a.timestamp;
        }

        /*
         * Stable fallback if two files somehow have the exact
         * same timestamp.
         */
        return b.name.localeCompare(a.name);
      })
      .map(({ id, name, url }) => ({
        id,
        name,
        url,
      }));

    return res.status(200).json({
      success: true,
      media,
    });
  } catch (err) {
    console.error("❌ GET media error:", err);

    return res.status(500).json({
      success: false,
      message: "Erreur lecture médias.",
    });
  }
});

// GET HOMEPAGE SLOTS (PUBLIC) - AUTO-CLEANS DELETED / MISSING IMAGES FROM JSON
router.get("/homepage-slots", (req, res) => {
  try {
    const config = readMediaConfig();
    const homepageConfig = config.homepage || {};
    const slots = {};
    let modified = false;

    for (const slotName of HOMEPAGE_SLOTS) {
      const slot = homepageConfig[slotName];

      if (slot && slot.file) {
        if (checkFileExists(slot.file)) {
          slots[slotName] = {
            ...slot,
            url: createMediaUrl(slot.file),
          };
        } else {
          homepageConfig[slotName] = null;
          slots[slotName] = null;
          modified = true;
        }
      } else {
        slots[slotName] = null;
      }
    }

    if (modified) {
      config.homepage = homepageConfig;
      writeMediaConfig(config);
    }

    return res.status(200).json({
      success: true,
      slots,
    });
  } catch (err) {
    console.error("❌ GET slots error:", err);

    return res.status(500).json({
      success: false,
      message: "Erreur lecture des images homepage.",
    });
  }
});

// GET FACADE GALLERY (PUBLIC) - AUTO-CLEANS DEAD MAIN & SUBIMAGE URLS FROM JSON
router.get("/gallery/facade", (req, res) => {
  try {
    const config = readMediaConfig();
    const rawFacades =
      config.homepage?.gallery?.facades || [];

    let modified = false;

    const facades = rawFacades.map((f) => {
      let item = { ...f };

      // 1. Verify main image exists on disk
      if (item.file && !checkFileExists(item.file)) {
        item.file = null;
        item.url = null;
        modified = true;
      } else {
        item.url = item.file
          ? createMediaUrl(item.file)
          : null;
      }

      // 2. Verify and filter subimages against actual disk files
      if (Array.isArray(item.subimages)) {
        const validSubimages = item.subimages.filter(
          (subfile) => {
            const exists = checkFileExists(subfile);

            if (!exists) {
              modified = true;
            }

            return exists;
          }
        );

        item.subimages = validSubimages;

        item.subimagesUrls = validSubimages.map(
          (subfile) => createMediaUrl(subfile)
        );
      } else {
        item.subimages = [];
        item.subimagesUrls = [];
      }

      return item;
    });

    if (modified) {
      if (!config.homepage) {
        config.homepage = {};
      }

      if (!config.homepage.gallery) {
        config.homepage.gallery = {};
      }

      config.homepage.gallery.facades = facades.map(
        ({ subimagesUrls, url, ...rest }) => rest
      );

      writeMediaConfig(config);
    }

    return res.status(200).json({
      success: true,
      facades,
      facade: facades[0] || null,
    });
  } catch (err) {
    console.error("❌ GET facade error:", err);

    return res.status(500).json({
      success: false,
      message: "Erreur lecture galerie façade.",
    });
  }
});

// SERVE MEDIA FILE (PUBLIC)
router.get("/file/:filename", (req, res) => {
  try {
    const filename = path.basename(req.params.filename);
    const filePath = path.join(projectsDirectory, filename);

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({
        success: false,
        message: "Média introuvable.",
        filename,
      });
    }

    return res.sendFile(filePath);
  } catch (err) {
    console.error("❌ GET file error:", err);

    return res.status(500).json({
      success: false,
      message: "Erreur serveur média.",
    });
  }
});

// MULTER SETUP
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, projectsDirectory);
  },

  filename: (req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase();

    /*
     * Date.now() is deliberately kept as the FIRST part
     * of the filename so GET /api/media can reliably sort
     * uploads from newest to oldest.
     */
    cb(
      null,
      `${Date.now()}-${crypto.randomBytes(8).toString("hex")}${ext}`
    );
  },
});

const upload = multer({
  storage,
});

// UPLOAD MEDIA (PROTECTED)
router.post(
  "/upload",
  requireAdminAuth,
  upload.array("media"),
  (req, res) => {
    try {
      const files = req.files || [];

      const media = files.map((file) => ({
        id: file.filename,
        name: file.filename,
        url: createMediaUrl(file.filename),
      }));

      return res.status(201).json({
        success: true,
        media,
      });
    } catch (err) {
      console.error("❌ POST upload error:", err);

      return res.status(500).json({
        success: false,
        message: "Erreur lors de l'upload.",
      });
    }
  }
);

// UPDATE HOMEPAGE SLOT (PROTECTED)
router.put(
  "/homepage-slots/:slot",
  requireAdminAuth,
  (req, res) => {
    try {
      const slotName = req.params.slot;

      if (!HOMEPAGE_SLOTS.includes(slotName)) {
        return res.status(400).json({
          success: false,
          message: "Slot invalide.",
        });
      }

      const {
        file,
        x,
        y,
        width,
        height,
        zoom,
        offsetX,
        offsetY,
      } = req.body || {};

      if (!file) {
        return res.status(400).json({
          success: false,
          message: "Fichier manquant.",
        });
      }

      const cleanFile = path.basename(file);

      if (!checkFileExists(cleanFile)) {
        return res.status(404).json({
          success: false,
          message:
            "Le fichier spécifié n'existe pas sur le serveur.",
        });
      }

      const config = readMediaConfig();

      if (!config.homepage) {
        config.homepage = {
          banner: null,
          introduction: null,
          finale: null,
          gallery: {
            facades: [],
          },
        };
      }

      config.homepage[slotName] = {
        file: cleanFile,
        x,
        y,
        width,
        height,
        zoom,
        offsetX,
        offsetY,
      };

      if (!writeMediaConfig(config)) {
        return res.status(500).json({
          success: false,
          message: "Impossible d'enregistrer le slot.",
        });
      }

      return res.json({
        success: true,
        message: "Slot enregistré.",
      });
    } catch (err) {
      console.error("❌ PUT slot error:", err);

      return res.status(500).json({
        success: false,
        message: "Erreur enregistrement du slot.",
      });
    }
  }
);

// UPDATE FACADE GALLERY (PROTECTED)
router.put(
  "/gallery/facade",
  requireAdminAuth,
  (req, res) => {
    try {
      const {
        file,
        title,
        description,
        index,
        x,
        y,
        width,
        height,
        zoom,
        offsetX,
        offsetY,
      } = req.body || {};

      if (!file) {
        return res.status(400).json({
          success: false,
          message: "Fichier manquant.",
        });
      }

      const cleanFile = path.basename(file);

      if (!checkFileExists(cleanFile)) {
        return res.status(404).json({
          success: false,
          message:
            "Le fichier spécifié n'existe pas sur le serveur.",
        });
      }

      const config = readMediaConfig();

      if (!config.homepage) {
        config.homepage = {
          banner: null,
          introduction: null,
          finale: null,
          gallery: {
            facades: [],
          },
        };
      }

      if (!config.homepage.gallery) {
        config.homepage.gallery = {
          facades: [],
        };
      }

      let facades =
        config.homepage.gallery.facades || [];

      const targetIndex =
        Number(index) || facades.length + 1;

      const existingIdx = facades.findIndex(
        (f) => Number(f.index) === targetIndex
      );

      const existingSubimages =
        (
          existingIdx !== -1 &&
          Array.isArray(facades[existingIdx].subimages)
            ? facades[existingIdx].subimages
            : []
        ).filter((sub) => checkFileExists(sub));

      const item = {
        file: cleanFile,
        title: title || "",
        description: description || "",
        index: targetIndex,
        x: Number(x) || 50,
        y: Number(y) || 50,
        width: Number(width) || 60,
        height: Number(height) || 45,
        zoom: Number(zoom) || 1.6667,
        offsetX: Number(offsetX) || 0,
        offsetY: Number(offsetY) || 0,
        subimages: existingSubimages,
      };

      if (existingIdx !== -1) {
        facades[existingIdx] = item;
      } else {
        facades.push(item);
      }

      config.homepage.gallery.facades = facades;

      if (!writeMediaConfig(config)) {
        return res.status(500).json({
          success: false,
          message:
            "Impossible d'enregistrer la galerie.",
        });
      }

      return res.json({
        success: true,
        facade: item,
      });
    } catch (err) {
      console.error(
        "❌ PUT facade gallery error:",
        err
      );

      return res.status(500).json({
        success: false,
        message:
          "Erreur enregistrement galerie.",
      });
    }
  }
);

// UPDATE SUBIMAGES (PROTECTED) - TOGGLE/MERGE & DISK EXISTENCE CHECK
router.put(
  "/gallery/subimages",
  requireAdminAuth,
  (req, res) => {
    try {
      const { index, filenames } = req.body || {};

      const targetIndex = Number(index);

      if (
        !Number.isInteger(targetIndex) ||
        targetIndex < 1
      ) {
        return res.status(400).json({
          success: false,
          message: "Index invalide.",
        });
      }

      const incomingFiles = (
        Array.isArray(filenames)
          ? filenames
          : [filenames]
      )
        .filter(Boolean)
        .map((f) => path.basename(f));

      if (!incomingFiles.length) {
        return res.status(400).json({
          success: false,
          message: "Aucun fichier spécifié.",
        });
      }

      const config = readMediaConfig();

      if (!config.homepage) {
        config.homepage = {};
      }

      if (!config.homepage.gallery) {
        config.homepage.gallery = {
          facades: [],
        };
      }

      let facades =
        config.homepage.gallery.facades || [];

      const existingIdx = facades.findIndex(
        (f) => Number(f.index) === targetIndex
      );

      if (existingIdx === -1) {
        return res.status(404).json({
          success: false,
          message:
            `Réalisation #${targetIndex} introuvable.`,
        });
      }

      let currentSubimages = (
        Array.isArray(
          facades[existingIdx].subimages
        )
          ? facades[existingIdx].subimages
          : []
      ).filter((file) =>
        checkFileExists(file)
      );

      incomingFiles.forEach((file) => {
        const existsOnDisk =
          checkFileExists(file);

        const foundIdx =
          currentSubimages.indexOf(file);

        if (foundIdx !== -1) {
          currentSubimages.splice(foundIdx, 1);
        } else if (existsOnDisk) {
          currentSubimages.push(file);
        }
      });

      facades[existingIdx].subimages =
        currentSubimages;

      config.homepage.gallery.facades =
        facades;

      if (!writeMediaConfig(config)) {
        return res.status(500).json({
          success: false,
          message:
            "Impossible d'enregistrer les sous-médias.",
        });
      }

      return res.json({
        success: true,
        message:
          `Sous-médias mis à jour pour la réalisation #${targetIndex} (${currentSubimages.length} valides).`,
        facade: facades[existingIdx],
        subimages: currentSubimages,
      });
    } catch (err) {
      console.error(
        "❌ PUT subimages error:",
        err
      );

      return res.status(500).json({
        success: false,
        message:
          "Erreur enregistrement sous-médias.",
      });
    }
  }
);

// BATCH DELETE FACADES (PROTECTED)
router.delete(
  "/gallery",
  requireAdminAuth,
  (req, res) => {
    try {
      const { indices } = req.body || {};

      if (
        !Array.isArray(indices) ||
        !indices.length
      ) {
        return res.status(400).json({
          success: false,
          message:
            "Indices invalides ou manquants.",
        });
      }

      const targetIndices =
        indices.map((i) => Number(i));

      const config = readMediaConfig();

      let facades = (
        config.homepage?.gallery?.facades || []
      )
        .filter(
          (f) =>
            !targetIndices.includes(
              Number(f.index)
            )
        )
        .map((item, idx) => ({
          ...item,
          index: idx + 1,
        }));

      if (!config.homepage) {
        config.homepage = {};
      }

      if (!config.homepage.gallery) {
        config.homepage.gallery = {};
      }

      config.homepage.gallery.facades =
        facades;

      if (!writeMediaConfig(config)) {
        return res.status(500).json({
          success: false,
          message:
            "Impossible de modifier la galerie.",
        });
      }

      return res.json({
        success: true,
        facades,
      });
    } catch (err) {
      console.error(
        "❌ DELETE batch gallery error:",
        err
      );

      return res.status(500).json({
        success: false,
        message:
          "Erreur suppression galerie.",
      });
    }
  }
);

// SINGLE DELETE FACADE (PROTECTED)
router.delete(
  "/gallery/:index",
  requireAdminAuth,
  (req, res) => {
    try {
      const targetIndex =
        Number(req.params.index);

      const config = readMediaConfig();

      let facades = (
        config.homepage?.gallery?.facades || []
      )
        .filter(
          (f) =>
            Number(f.index) !== targetIndex
        )
        .map((item, idx) => ({
          ...item,
          index: idx + 1,
        }));

      if (!config.homepage) {
        config.homepage = {};
      }

      if (!config.homepage.gallery) {
        config.homepage.gallery = {};
      }

      config.homepage.gallery.facades =
        facades;

      if (!writeMediaConfig(config)) {
        return res.status(500).json({
          success: false,
          message:
            "Impossible de modifier la galerie.",
        });
      }

      return res.json({
        success: true,
        facades,
      });
    } catch (err) {
      console.error(
        "❌ DELETE single gallery error:",
        err
      );

      return res.status(500).json({
        success: false,
        message:
          "Erreur suppression galerie.",
      });
    }
  }
);

// DELETE RAW MEDIA FILE (PROTECTED) - CASCADES & SCRUBS ALL REFERENCES
router.delete(
  "/:id",
  requireAdminAuth,
  (req, res) => {
    try {
      const filename =
        path.basename(req.params.id);

      const filePath =
        path.join(
          projectsDirectory,
          filename
        );

      // 1. Delete file from disk
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
      }

      // 2. Cascade cleanup in media.json
      const config = readMediaConfig();

      let modified = false;

      if (config.homepage) {
        for (const slot of HOMEPAGE_SLOTS) {
          if (
            config.homepage[slot] &&
            config.homepage[slot].file ===
              filename
          ) {
            config.homepage[slot] = null;
            modified = true;
          }
        }

        if (
          Array.isArray(
            config.homepage.gallery?.facades
          )
        ) {
          config.homepage.gallery.facades =
            config.homepage.gallery.facades.map(
              (f) => {
                let updated = { ...f };

                if (
                  updated.file === filename
                ) {
                  updated.file = null;
                  modified = true;
                }

                if (
                  Array.isArray(
                    updated.subimages
                  ) &&
                  updated.subimages.includes(
                    filename
                  )
                ) {
                  updated.subimages =
                    updated.subimages.filter(
                      (sub) =>
                        sub !== filename
                    );

                  modified = true;
                }

                return updated;
              }
            );
        }
      }

      if (modified) {
        writeMediaConfig(config);
      }

      return res.json({
        success: true,
        message:
          "Média supprimé et références nettoyées.",
      });
    } catch (err) {
      console.error(
        "❌ DELETE media error:",
        err
      );

      return res.status(500).json({
        success: false,
        message:
          "Erreur suppression média.",
      });
    }
  }
);

module.exports = router;